### ISSUE TITLE
Error when running `:Conflicted`

### ISSUE THREAD

**Issue by jakecraige** [christoomey/vim-conflicted#10]
I just tried using this plugin and when I run `:Conflicted` I get this error in the prompt

```
"db/migrate/20150413215433_create_interests.rb" 11L, 263C
Error detected while processing function <SNR>90_Conflicted..<SNR>90_Merger..<SNR>34_Diff:
line    7:
"fugitive:///Users/jakecraige/Work/apps/glassbreakers/.git//1/db/migrate/20150413215433_create_interests.rb" --No lines in buffer-- ((1) of 5)
```

It still opens up the 3 tabs but the "working" tab doesn't have the 3 splits. Do you know what this is?

**Comment by christoomey** [comment]
Looks like a fugitive error. Can you try running just `:Gdiff` and let me know what the output is?

**Comment by jakecraige** [comment]
Interesting, I get this when running that.

```
Error detected while processing function <SNR>34_Diff:
line    7:
E480: No match: `=fugitive#buffer().repo().translate(s:buffer().expand(':2'))`
```

**Comment by christoomey** [comment]
Yep, that's definitely in fugitive. Unfortunately I don't have much knowledge about the inner workings of it to help out here. Might be worth opening an issue on fugitive's repo. I'm going to close this now, but please feel free to reopen or comment if you feel there is something specific to Conflicted involved.
