### ISSUE TITLE
Windows are line up in vertical order, how can it be changed to horizontal?

### ISSUE THREAD

**Issue by whitesiroi** [christoomey/vim-conflicted#11]
Hello,

Thank you for your plugin.
I want to line up windows like you have https://github.com/christoomey/vim-conflicted/raw/master/images/tablabel-terminal.png

Your windows are from left to right, but mines are from top to bottom. Maybe, you know how can I fix it?

Thank you & best regards,
Artem

**Comment by christoomey** [comment]
Hey @whitesiroi, I'm guessing this is related to fugitvie.vim functionality, discussed [here](https://github.com/tpope/vim-fugitive/issues/589). Looks like you should be able to set `:set diffopt+=vertical` to solve.

**Comment by whitesiroi** [comment]
Aaa, @christoomey thank you very much for your help. It does work perfectly.
