### ISSUE TITLE
In Neovim it's splitting into rows instead of columns

### ISSUE THREAD

**Issue by brodock** [christoomey/vim-conflicted#15]
I tried the `:Conflicted` with Neovim and instead of columns I got the 3 merge in rows. Do you happen to know if this is an issue with `git-fugitive` or is it `vim-conflicted` that need to behave differently?

**Comment by christoomey** [comment]
Hi @brodock, I'm not certain where this would be coming from, but I believe that the `diffopt` setting will control this. Specifically, you should be able to run `set diffopt+=vertical` to force column based diffs (or possibly the reverse?). You can check the current value and where it was set by running `:verbose set diffopt`. In my case I can see that it was last set in my vimrc, with the value of `diffopt=filler,vertical,iwhite`, although looking at it I can see that I didn't set the vertical bit.

Either way, I would expect that this plugin is the cause, so I'm going to close based on that, but please feel free to comment or reopen if you think I've missed anything.
