### ISSUE TITLE
Usage as mergetool

### ISSUE THREAD

**Issue by p-o-bcak** [christoomey/vim-conflicted#16]
Hi there, the plugin sounds promising. But it not yet clear to me how to use it in combination with `git mergetool`? I plan to directly jump into your plugin when using that command to resolve merge conflicts.
When only using the command `Conflicted` the current window is used, which looks weird when starting from the diff mode in vim. Thank you!

**Comment by christoomey** [comment]
Hi @p-o-bcak, I'm not entirely sure what all is involved in setting up a mergetool or if this plugin would be amenable to usage as a git mergetool in its current form.

That said, I use the command via a git alias which handles everything for me, and allows me to start up from the shell. I've just [added a section to the README](https://github.com/christoomey/vim-conflicted#from-git) about how to configure this.

I'm going to close this now as I don't necessarily see this as a bug or issue (although I'd be open to reviewing a PR related to proper `mergetool` support as an enhancement), and in the hopes that the above will cover what you need, but please feel free to comment or reopen if you still have trouble.
