### ISSUE TITLE
E15: Invalid expression: pyeval('powerline.new_window()')%{ConflictedVersion()}

### ISSUE THREAD

**Issue by albasili** [christoomey/vim-conflicted#22]
I've recently updated my plugins as well as my Debian box to "buster" and suddenly I have this error which is caused by this configuration in my `.vimrc`:

```
set stl+=%{ConflictedVersion()}
```

The `ConflictedVersion()` is apparently available in the `vim-conflicted/plugin/conflicted.vim` file and I suspect it always been there.

The error appears when I source the file through `:source %` which is something I regularly do after tweaking my config. It is not present when I launch `vim`.

Any advice?

**Comment by christoomey** [comment]
Hmm, I think you may have run into an incompatibility between the newer version of powerline and this statusline config. I don't think this is specific to the plugin, but instead is likely a more general issue realted to using powerline _and_ setting `stl` ("statusline") config manually. I'd suggest poking at their docs to see if anything stands out.

I'm going to close this now as I'm pretty sure the issue doesn't lie here, but feel free to comment or re-open if you think I'm mistaken.
