### ISSUE TITLE
Add user autocmd event when conflicted started

### ISSUE THREAD

**Issue by BlueDrink9** [christoomey/vim-conflicted#23]
When using conflicted, there are a few settings I want to set. These often override settings I use in other vim contexts. It would be great to be able to set them in an autocmd, to activate only when starting conflicted.

**Comment by christoomey** [comment]
Hmm, interesting idea. In general, I prefer to keep things as minimal as possible in the plugin code itself assuming there is a way to implement things outside the plugin. In this case, I wonder if you could wrap the `Conflicted` command to set things.  As a rough example:

``` vim
function! MyConflicted()
  Conflicted
  nmap <buffer> <leader>go :DoAThing<cr>
  setlocal winheight=10
endfunction
```

The mapping and setting there would both be local to the central buffer of the workflow. If that wouldn't work for you, I'd be interested to know a bit more about the specific settings or workflow you're trying to enable.

**Comment by BlueDrink9** [comment]
I understand the concern about the plugin code, but since you don't set a filetype for conflicted buffers, it makes sense to have some other way for users to know they are in a conflicted buffer. Also, it's only one extra line!

In the bootstrap function:

`doautocmd User VimConflicted`

My perspective: The wrapper would work, but that pushes a lot of complexity to the user setup. It forces changes to aliases for git, shell, changes to user mappings, and we now have to learn a new command to use. It also leaves two functsion in the global namespace, one of which may be much less discoverable, or it may be confusing which to use for users that didn't write the rc themselves recently.

**Comment by BlueDrink9** [comment]
If you want, I'd be happy to PR, but I figured since it was such a small change (outside of documentation), you'd be happy to do it yourself.

**Comment by BlueDrink9** [comment]
@christoomey since this is only one extra line + documentation, would you be happy to have this change integrated? Happy to PR if that makes your job easier

**Comment by BlueDrink9** [comment]
@christoomey would you accept a PR to add this feature? It isn't currently something users can implement in their own configs
