### ISSUE TITLE
fugitive throwing "No matching autocommands" error

### ISSUE THREAD

**Issue by JESii** [christoomey/vim-conflicted#27]
In. the past week or two, running `Conflicted` in my repo shows the folllowing message 
```
"fugitive:///Users/jseidel/bw/order-tunnel-web/.git//3/src/components/SaveDraftModal/SaveDraftModal.js" 588 lines --0%--
No matching autocommands
```
and then prompts me to `Press ENTER or type a command...`.
I'm guessing this is because of a recent update to fugitive? Didn't have time to track this down, but will if I get a change -- fortunately, it's not a blocker, just an extra keypress.
Thanks for these commands -- I use them daily!!!

**Comment by christoomey** [comment]
Hey @JESii, nice to hear from you, although sorry you're running into issues. I'm a bit slower to update so haven't run into this myself, but please do let me know if you figure anything else out.

**Comment by buys-fran** [comment]
I get the same error.
However I also see this error when I use fugitive to create a commit message (cc).

**Comment by JESii** [comment]
Hey, @christoomey Haven't seen these in quite a while... probably because of udpates to fugitive? So I'll just close this.
Hope you're doing well; congrats on the CTO position!
